version: '3.8'
services:
  nodejs:
    build: 
      context: .
    image: jahid094/restservice
    networks:
      - frontend
      - backend
    environment:
    
      - MYSQL_HOST=localhost
      - MYSQL_USER=root
      - MYSQL_PASS=
      - MYSQL_DB=node_mysql_api
   
    ports:
      - "3001:5000"
    container_name: api-nodejs-app
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=moeuser
      - MYSQL_PASSWORD=moepass 
      - MYSQL_DATABASE=moe_db
    container_name: api-mysql-app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "3002:80"
    environment:
      - PMA_HOST=api-mysql-app
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: my-phpmyadmin-app
networks:
  frontend:
  backend: